import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { tokenize } from "../src/align/normalize.js";
import { alignWords } from "../src/align/edit-distance.js";
const llm = JSON.parse(readFileSync(resolve("./intermediates/llm-test/chunk_000_parsed.json"), "utf-8")) as any;
const asr = JSON.parse(readFileSync(resolve("./intermediates/timestamped-test/timestamped.json"), "utf-8")) as any;
const W = asr.words;
const norm = (t: string) => t.toLowerCase().replace(/^[^a-z0-9']+|[^a-z0-9']+$/gi, "");
console.log("asr[14..35]:");
for (let i = 14; i < 36; i++) console.log(`  [${i}] "${W[i].text}"@${W[i].start.toFixed(2)} norm=${norm(W[i].text)}`);
const seg3 = llm.segments[3];
console.log("\nseg3 text:", JSON.stringify(seg3.text), "coarse", seg3.startSec);
const t3 = tokenize(seg3.text);
console.log("seg3 norms:", t3.map((t: any) => t.norm).join("|"));
// window asr[21:71]
const win = W.slice(21, 71).map((w: any) => ({ text: w.text, start: w.start, end: w.end, norm: norm(w.text) }));
const r = alignWords(t3, win);
console.log("\nalign seg3 vs asr[21:71]:", { exact: r.exactMatches, fuzzy: r.fuzzyMatches, subs: r.substitutions, ins: r.insertions, del: r.deletions });
let last = -1;
for (const op of r.ops) if (op.type === "match" || op.type === "substitute") last = Math.max(last, op.asr);
console.log("lastConsumed (window idx):", last, "→ asr idx", 21 + last, "→ time", last >= 0 ? W[21 + last].start.toFixed(2) : "n/a");
console.log("ops:", r.ops.map((o: any) => o.type + (o.asr !== undefined ? `(${o.asr})` : "")).join(" "));
